- descriptor: "pip-services-container:container-info:default:default:1.0"
  name: "pip-services-sessions"
  description: "Sessions microservice"

- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-sessions:persistence:file:default:1.0"
  path: "./data/sessions.json"

- descriptor: "pip-services-sessions:controller:default:default:1.0"

- descriptor: "pip-services-sessions:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 3000
